[package]
name = "infoskjerm"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
image = "0.24.7"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
slint = "1.0.0"
tiny-skia = "0.11.1"
openssl = { version = "0.10", features = ["vendored"] }

[build-dependencies]
slint-build = "1.0"
