[package]
name = "infoskjerm"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
image = "0.24.7"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
slint = "1.3.2"
rust-embed = "6.8.1"
log = "0.4.20"
env_logger = "0.10.1"

# Vendored OpenSSL seems to be required for building on Linux on GHA, but not for Windows or Mac. Maybe this can be fixed some other way
[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[build-dependencies]
slint-build = "1.3.2"
