# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial


[target.arm-unknown-linux-gnueabihf]
image = "ghcr.io/slint-ui/slint/armv7-unknown-linux-gnueabihf"
pre-build = [
    "sudo apt-get install --assume-yes --no-install-recommends libssl-dev pkg-config",
]

[build.env]
passthrough = [
    "SLINT_NO_QT",
    "SLINT_STYLE",
    "SLINT_TEST_FILTER",
    "SLINT_INTERPRETER_ERROR_WHITELIST",
]
