import { Button, VerticalBox } from "std-widgets.slint";

import { GridBox } from "std-widgets.slint";


export component AppWindow inherits Window {
    title: "Infoskjerm";
    //todo: set these programtically
    width: 768px;
    height: 1024px;
    background:  #030201;

    in property <string> time: "12:34:56";
    in property <string> xkcdTitle: "Lorem ipsum";
    in property <image> xkcdImage: @image-url("./img/xkcd.png");
    in property <string> xkcdFlavorText: "Dolor sit amet";

    
    GridLayout{
        padding-top: 3rem;
        spacing: 5px;
        Row {
            Text{
                color: whitesmoke;
                colspan: 2;
                text: "Trondheimkontorets infoskjerm \n (work in progress)";
                font-family: "sans";
                font-size: 4rem;
                horizontal-alignment: center;
            }
        }
     
        Row{
            Rectangle {
                background: red;
                Text{
                    font-size: 2rem;
                    text: "Busstider?";
                }
            }
            Rectangle {
                background: blue;
                Text{
                    font-size: 2rem;
                    text: "Event-kalender?";
                }
            }
        }
        Row {
            Rectangle {
                background: green;
                Text{
                    font-size: 2rem;
                    text: "Slack-aktivitet?";
                }
            }
            Rectangle {
                background: violet;
                Text{
                    font-size: 2rem;
                    text: "Værmelding?";
                }
            }
        }
        Row {
            VerticalBox {
                colspan: 2;
                spacing: 0;
                alignment: start;
                Image {
                    max-height: 25rem;
                    source: xkcdImage;
                }
                Text {
                    horizontal-alignment: center;
                    color: whitesmoke;
                    text: xkcdTitle;
                    font-weight: 1000;
                }
                Text {
                    wrap: word-wrap;
                    horizontal-alignment: center;
                    color: whitesmoke;
                    text: xkcdFlavorText;
                }
            }
        }
        Row {
            Text {
                color: whitesmoke;
                colspan: 2;
                horizontal-alignment: right;
                font-size: 3rem;
                font-family: "sans";
                text: time;
            }
        }
        
    }
}