import { HorizontalBox, VerticalBox } from "std-widgets.slint";
export struct FoodTracking {
    resturant_name: string,
    minutes_remaining: string,
    status: string,
    active: bool,
}

export component FoodTrackerWidget{
    in property <FoodTracking> tracking;
        Rectangle {
            height: 8rem;
            background: #FFFFFF;
            border-radius: 32px;
            HorizontalBox {
                alignment: space-around;
                VerticalBox {
                    Text {
                        text: "Fra";
                        color: #1F0D8D;
                        font-size: 1.5rem;
                    }
                    Text {
                        text: tracking.resturant_name;
                        color: #000000;
                    }
                }
                VerticalBox {
                    Text {
                        text: "Status";
                        color: #1F0D8D;
                        font-size: 1.5rem;
                    }
                    Text {
                        text: tracking.status;
                        color: #000000;
                    }
                }
                VerticalBox {
                    Text {
                        text: "ETA";
                        color: #1F0D8D;
                        font-size: 1.5rem;
                    }
                    Text {
                        //text: tracking.resturant_name;
                        text: tracking.minutes-remaining + " minutter";
                        color: #000000;
                    }
                }
                Image {
                    source: @image-url("../img/wolt.png");
                    width: 100px;
                }
    
            }
        }
}