import { HorizontalBox, VerticalBox } from "std-widgets.slint";
export struct FoodTracking {
    resturant_name: string,
    minutes_remaining: string,
    status: string,
    active: bool,
}

export component FoodTrackerWidget{
    in property <FoodTracking> tracking: {
        resturant_name: "Burger King",
        minutes-remaining: "5",
        status: "Transport",
        active: true
    };
        Rectangle {
            height: 10rem;
            min-height: 8rem;
            background: #FFFFFF;
            border-radius: 32px;
            HorizontalLayout {
                alignment: space-around;
                VerticalLayout {
                    alignment: center;
                    spacing: 0.25rem;
                    Text {
                        text: "Fra";
                        color: #1F0D8D;
                        font-size: 2rem;
                    }
                    Text {
                        text: tracking.resturant_name;
                        color: #000000;
                        font-size: 3rem;
                    }
                }
                VerticalLayout {
                    alignment: center;
                    spacing: 0.25rem;
                    Text {
                        text: "Status";
                        color: #1F0D8D;
                        font-size: 2rem;
                    }
                    Text {
                        text: tracking.status;
                        color: #000000;
                        font-size: 3rem;
                    }
                }
                VerticalLayout {
                    alignment: center;
                    spacing: 0.25rem;
                    Text {
                        text: "ETA";
                        color: #1F0D8D;
                        font-size: 2rem;
                    }
                    Text {
                        text: tracking.minutes-remaining + " minutter";
                        color: #000000;
                        font-size: 3rem;
                    }
                }
                Image {
                    source: @image-url("../img/wolt.png");
                    width: 100px;
                }
    
            }
        }
}