import { VerticalBox, HorizontalBox } from "std-widgets.slint";

export struct Forecast {
    temp: string,
    icon: image,
    precipitation: string,
}

component ForecastCell {
    in property <Forecast> forecast;
    in property <string> heading;

    VerticalBox {
        HorizontalBox {
            alignment: center;
            Image {
                max-height: 8.75rem;
                max-width: 8.75rem;
                source: forecast.icon;
            }

            VerticalBox {
                Text {
                    color: #FEFBE6;
                    text: forecast.temp + "°";
                    font-size: forecast.precipitation != 0 ? 4rem : 5rem;
                    horizontal-alignment: center;
                }

                if forecast.precipitation != 0: Text {
                    color: #FEFBE6;
                    text: forecast.precipitation + "mm";
                    font-size: 1.5rem;
                    horizontal-alignment: center;
                }
            }
        }

        Text {
            color: #FEFBE6;
            text: heading;
            font-size: 2.5rem;
            horizontal-alignment: center;
        }
    }
}

export component ForecastWidget {
    in property <Forecast> now: {
        temp: "-1",
        precipitation: "0",
        icon: @image-url("../img/weather/partlycloudy_day.png")
    };
    in property <Forecast> tomorrow: {
        temp: "10",
        precipitation: "2",
        icon: @image-url("../img/weather/partlycloudy_day.png")
    };

    HorizontalBox {
        width: 100%;
        ForecastCell {
            forecast: now;
            heading: "Nå";
        }

        ForecastCell {
            forecast: tomorrow;
            heading: "I morgen";
        }
    }
}
