import { Button, VerticalBox } from "std-widgets.slint";

import { GridBox } from "std-widgets.slint";
import { XkcdWidget } from "xkcdwidget.slint";
import { WeatherWidget } from "weatherwidget.slint";



export component MainWindow inherits Window {
    title: "Infoskjerm";
    //todo: set these programtically
    width: 540px;
    height: 960px;
    background:  #030201;

    in property <string> time: "12:34:56";

    in property <string> weather: "Fint vær";

    in property <string> xkcdTitle: "Lorem ipsum";
    in property <string> xkcdFlavorText: "Dolor sit amet";
    in property <image> xkcdImage: @image-url("./img/xkcd.png");


    
    GridLayout{
        Rectangle {
            background: red;
            Text{
                font-size: 2rem;
                text: "Busstider?";
            }
        }
        Rectangle {
            background: blue;
            Text{
                font-size: 2rem;
                text: "Event-kalender?";
             }
        }
        Rectangle {
            row: 1;
            background: green;
            Text{
                font-size: 2rem;
                text: "Slack-aktivitet?";
            }
        }
        
        WeatherWidget {
            row: 1;
            col: 1; 
            weather: weather;
        }
    
        XkcdWidget {
            row: 2;
            colspan: 2;
            max-height: 30rem;
            image: xkcdImage;
            flavorText: xkcdFlavorText;
            title: xkcdTitle;
            }

        Text {
            row: 3;
            colspan: 2;
            color: whitesmoke;
            horizontal-alignment: right;
            font-size: 4rem;
            font-family: "sans";
            text: time;
        }

    }
}