import { Button, VerticalBox } from "std-widgets.slint";

import { GridBox , HorizontalBox} from "std-widgets.slint";
import { Xkcd, XkcdWidget } from "xkcdwidget.slint";
import { ForecastWidget, Forecast } from "forecastwidget.slint";
import { FoodTrackerWidget, FoodTracking} from "foodtrackerwidget.slint";
import { CalendarWidget, Event } from "calendarwidget.slint";
import "./assets/Bagoss.ttf";
import "./assets/FiraMono-Regular.ttf";

export component MainWindow inherits Window {
    in property <string> time: "12:34";
    in property <string> date: "Mandag 5. august";
    in property <Forecast> todayForecast: {
        temp: "-1",
        precipitation: "2",
        icon: @image-url("../img/weather/partlycloudy_day.png")
    };
    in property <Forecast> tomorrowForecast: {
        temp: "-1",
        precipitation: "2",
        icon: @image-url("../img/weather/partlycloudy_day.png")
    };
    in property <Xkcd> xkcd: {
        title: "Lorem Ipsum",
        image: @image-url("../img/xkcd2.png"),
        flavor_text: "Dolor sit ametDolor sit ametDolor sit ametDolor sit ametDolor sit ametDolor sit ametDolor sit ametDolor sit ametDolor sit ametDolor sit ametDolor sit ametDolor sit ametDolor sit amet"
    };

    in property <FoodTracking> foodTracking: {
        active: false,
        resturant_name: "McDonalds",
        minutes_remaining: "5",
    };

    in property <[Event]> events: [{
        summary: "Placeholder calendar event",
        date: "31. April",
    }];

    title: "Infoskjerm";
    //TODO: Set programmatically?
    no-frame: true;
    //width: 576px;
    //height: 1024px;
    background: #0C0C27;

    default-font-family: "Bagoss";
    VerticalLayout {
        width: 100%;
        padding: 3rem;
        alignment: space-between;

        HorizontalLayout {
            width: 100%;
            alignment: space-between;
            Text {
                font-size: 2rem;
                color: #FEFBE6;
                text: date;
            }

            Text {
                color: #FEFBE6;
                font-size: 2rem;
                text: time;
            }
        }

        ForecastWidget {
            today: todayForecast;
            tomorrow: tomorrowForecast;
        }

        if foodTracking.active: FoodTrackerWidget {
            tracking: foodTracking;
        }

        CalendarWidget {
            events: events;
            meetings: [];
        }

        XkcdWidget {
            max-height: 30rem;
            xkcd: xkcd;
        }
    }
}
