import { Button, VerticalBox } from "std-widgets.slint";

import { GridBox , HorizontalBox} from "std-widgets.slint";
import { XkcdWidget } from "xkcdwidget.slint";
import { WeatherWidget, Forecast } from "weatherwidget.slint";

export component MainWindow inherits Window {
   in property <string> time: "12:34:56";

    in property <[Forecast]> forecasts: [{
        time: "12:00",
        temp: "3.0",
        icon: @image-url("../img/weather/fog.png"),
        precipitation: "4.0"
    }];

    //TODO: refactor into custom struct
    in property <string> xkcdTitle: "Lorem ipsum";
    in property <string> xkcdFlavorText: "Dolor sit amet";
    in property <image> xkcdImage: @image-url("../img/xkcd.png");

    title: "Infoskjerm";
    //todo: set these programtically
    // width: 540px;
    // height: 960px;
    background:  #030201;
    default-font-family: "sans";


    
    VerticalLayout{
        alignment: space-between;

        WeatherWidget {
            forecasts: forecasts;
        }
        
        XkcdWidget {
            max-height: 30rem;
            image: xkcdImage;
            flavorText: xkcdFlavorText;
            title: xkcdTitle;
            }

        HorizontalBox {
            alignment: space-between;
            VerticalLayout {
                alignment: end;
                spacing: -3px;
                padding-bottom: 6px;
                Text {
                    font-size: 2.4rem;
                    font-weight: 700;
                    horizontal-alignment: center;
                    color: whitesmoke;
                    text: 17;
                }
                Text {
                    font-size: 1.1rem;
                    horizontal-alignment: center;
                    color: whitesmoke;
                    text: "AUG";
                }
            }   
    
            Text {
                color: whitesmoke;
                horizontal-alignment: right;
                font-size: 4rem;
                text: time;
            }
    }

        


        
    }
}