export struct Forecast {
    time: string,
    temp: string,
    icon: image,
    precipitation: string,
}

component WeatherLine {
    in property <Forecast> forecast;
    HorizontalLayout {
        spacing: 1.5rem;
        alignment: center;
        Text {
            color: whitesmoke;
            text: forecast.time;
            font-size: 2rem;
        }

        Image {
            max-height: 3rem;
            max-width: 3rem;
            source: forecast.icon;
        }

        Text {
            color: whitesmoke;
            text: forecast.temp + "°c";
            font-size: 2rem;
        }

        Text {
            color: whitesmoke;
            text: forecast.precipitation + "mm";
            font-size: 2rem;
        }
    }
}

export component WeatherWidget { 
    in property <[Forecast]> forecasts;
    VerticalLayout {
        alignment: start;
        padding-top: 2rem;
        Text {
            color: whitesmoke;
            font-size: 4rem;
            text: "Været i dag:";
            horizontal-alignment: center;
        }
        for f in forecasts : WeatherLine {
           forecast: f;
        }
    }
    
 }