export struct Forecast {
    time: string,
    temp: string,
    icon: image,
    precipitation: string,
}


component WeatherRow {
    in property <Forecast> forecast;
    
    HorizontalLayout {
        spacing: 1.5rem;
        alignment: center;
        Text {
            color: #FEFBE6;
            text: forecast.time;
            font-size: 2rem;
        }

        Image {
            max-height: 3rem;
            max-width: 3rem;
            source: forecast.icon;
        }

        Text {
            color: #FEFBE6;
            text: forecast.temp + "°c";
            font-size: 2rem;
        }

        Text {
            color: #FEFBE6;
            text: forecast.precipitation + "mm";
            font-size: 2rem;
        }
    }
}

component WeatherColumn {
    in property <[Forecast]> forecasts;
    in property <string> heading;

    VerticalLayout {
        alignment: start;
        padding-top: 2rem;
        Text {
            color: #FEFBE6;
            font-size: 4rem;
            text: heading;
            horizontal-alignment: center;
        }
        
        for f in forecasts : WeatherRow {
           forecast: f;
        }
    }
    
}

export component WeatherWidget { 
    in property <[Forecast]> todayForecast;
    in property <[Forecast]> tomorrowForecast;

    HorizontalLayout {
       WeatherColumn {
           forecasts: todayForecast;
           heading: "Været i dag";
        }
        WeatherColumn {
            forecasts: tomorrowForecast;
            heading: "Været i morgen";
         }
   
    }
 }