import { VerticalBox } from "std-widgets.slint";

export struct Xkcd {
        title: string,
        image: image,
        flavor_text: string,
}

export component XkcdWidget {
    in property <Xkcd> xkcd ;
        VerticalBox {
            spacing: 0;
            alignment: start;
            Image {
                source: xkcd.image;
            }
            Text {
                horizontal-alignment: center;
                color: whitesmoke;
                text: xkcd.title;
                font-weight: 1000;
            }
            Text {
                wrap: word-wrap;
                horizontal-alignment: center;
                color: whitesmoke;
                text: xkcd.flavor-text;
            }
        }
 }