import { VerticalBox } from "std-widgets.slint";

export struct Xkcd {
        title: string,
        image: image,
        flavor_text: string,
}

export component XkcdWidget {
    in property <Xkcd> xkcd ;
        VerticalLayout {
            spacing: 0;
            width: 75%;

            Image {
                source: xkcd.image;
            }
            Text {
                horizontal-alignment: center;
                color: #FEFBE6;
                text: xkcd.title;
                font-weight: 1000;
            }
            Text {
                wrap: word-wrap;
                horizontal-alignment: center;
                color: #FEFBE6;
                text: xkcd.flavor-text;
                font-family: "sans";

            }
        }
 }