name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install ARM Target
      run: rustup target add arm-unknown-linux-gnueabihf
    - name: Install Cross
      run: cargo install Cross
    - name: Build
      run: cross build --release --target=arm-unknown-linux-gnueabihf
